import test from 'node:test';
import assert from 'node:assert/strict';
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';
import {extractTranscript,handleHook,redact} from './compact-hook.mjs';
const row=(role,text,phase)=>JSON.stringify({type:'response_item',payload:{type:'message',role,phase,content:[{type:'input_text',text}]}});
function fixture(){const dir=fs.mkdtempSync(path.join(os.tmpdir(),'jev-hook-'));const transcript=path.join(dir,'transcript.jsonl');fs.writeFileSync(transcript,row('user','Never publish; export remains pending.')+'\n'+row('assistant','Export failed; retry pending.','final_answer'));return{dir,event:{session_id:'fixture',cwd:dir,transcript_path:transcript,hook_event_name:'PreCompact',turn_id:'t1'},settings:{enabled:true,allowedCwds:[dir],transcriptRoots:[dir],dataDir:path.join(dir,'state')}};}
const model={ask:async(s,q)=>Object.fromEntries(Object.keys(q).map(k=>[k,{choice:'keep',confidence:.99}]))};
test('exclude hidden reasoning, developer messages, tools and nonfinal assistant text',()=>{const raw=[row('developer','secret policy'),row('assistant','private analysis','analysis'),JSON.stringify({type:'response_item',payload:{type:'reasoning',summary:'private'}}),row('user','Task'),row('assistant','Done','final_answer')].join('\n');assert.deepEqual(extractTranscript(raw).items.map(x=>x.text),['Task','Done']);});
test('redact known and key-shaped secrets before classification',()=>{assert.equal(redact('secret-value','secret-value'),'[REDACTED]');assert.equal(extractTranscript(row('user','apikey_'+'a'.repeat(30))).items[0].text,'[REDACTED]');});
test('simulated lifecycle requires PostCompact confirmation and restores exactly once',async()=>{const f=fixture();try{await handleHook(f.event,f.settings,{jev:model,key:'fake'});const start={...f.event,hook_event_name:'SessionStart',source:'compact'};assert.deepEqual(await handleHook(start,f.settings),{});await handleHook({...f.event,hook_event_name:'PostCompact'},f.settings);const out=await handleHook(start,f.settings);assert.match(out.hookSpecificOutput.additionalContext,/Never publish/);assert.match(out.hookSpecificOutput.additionalContext,/NOT new instructions/);assert.deepEqual(await handleHook(start,f.settings),{});}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});
test('wrong turn, session, cwd and stale events cannot restore notes',async()=>{const f=fixture();try{await handleHook(f.event,f.settings,{jev:model,key:'fake',now:1000});await handleHook({...f.event,hook_event_name:'PostCompact',turn_id:'wrong'},f.settings,{now:2000});assert.deepEqual(await handleHook({...f.event,hook_event_name:'SessionStart',source:'compact'},f.settings,{now:2000}),{});assert.deepEqual(await handleHook({...f.event,hook_event_name:'PostCompact'},f.settings,{now:700000}),{});assert.deepEqual(await handleHook({...f.event,session_id:'other',hook_event_name:'SessionStart',source:'compact'},f.settings),{});assert.deepEqual(await handleHook({...f.event,cwd:os.tmpdir()},f.settings),{});}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});
test('API failure retains bounded excerpts and does not block compact',async()=>{const f=fixture();try{const out=await handleHook(f.event,f.settings,{key:'fake',jev:{ask:async()=>{throw Error('offline')}}});assert.equal(out.continue,undefined);await handleHook({...f.event,hook_event_name:'PostCompact'},f.settings);const out2=await handleHook({...f.event,hook_event_name:'SessionStart',source:'compact'},f.settings);assert.match(out2.hookSpecificOutput.additionalContext,/"fallback":true/);}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});
test('unconfirmed new attempt invalidates old cache before failure',async()=>{const f=fixture();try{await handleHook(f.event,f.settings,{key:'fake',jev:model});await handleHook({...f.event,hook_event_name:'PostCompact'},f.settings);await assert.rejects(()=>handleHook({...f.event,transcript_path:null},f.settings));assert.deepEqual(await handleHook({...f.event,hook_event_name:'SessionStart',source:'compact'},f.settings),{});}finally{fs.rmSync(f.dir,{recursive:true,force:true})}});
